### ISSUE TITLE
ROGER: Almacenar en SQLite la ubicación en ese momento del jugador.

### ISSUE THREAD

**Issue by Jve386** [Jve386/NativeNinjas-Apps#18]

**Comment by rogeruoc21** [comment]
**Funcion: Modelo Partida/Get & Set**

```
 public double getLatitud() {
        return latitud;
    }

    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }

    public double getLongitud() {
        return longitud;
    }

    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }

```
**Modelo/Dao/PartidaDao** Aañadimos las columnas necesarias en todas las funciones CRUD

` @Override
    public void insertar(Partida partida) throws SQLiteException {
        SQLiteDatabase db = this.getWritableDatabase();
        ContentValues values = new ContentValues();
        values.put(COLUMN_USUARIO, partida.getUsuarioId());
        values.put(COLUMN_MONEDAS, partida.getMonedas());
        values.put(COLUMN_FECHA, partida.getFecha());
        **values.put(COLUMN_LATITUD, partida.getLatitud());
        values.put(COLUMN_LONGITUD, partida.getLongitud());**
        db.insert(TABLE_PARTIDA, null, values);
        db.close();
    }

    @Override
    public void modificar(Partida partida) throws SQLiteException {
        SQLiteDatabase db = this.getWritableDatabase();
        ContentValues values = new ContentValues();
        values.put(COLUMN_MONEDAS, partida.getMonedas());
        **values.put(COLUMN_LATITUD, partida.getLatitud());
        values.put(COLUMN_LONGITUD, partida.getLongitud());**
        db.update(TABLE_PARTIDA, values, COLUMN_ID + "=?", new String[]{Integer.toString(partida.getId())});
        db.close();
    }

  

    @Override
    public List<Partida> listarTodos() throws SQLiteException {
        SQLiteDatabase db = this.getReadableDatabase();
        ArrayList<Partida> array_list = new ArrayList<Partida>();
        Cursor res = db.rawQuery("select * from " + TABLE_PARTIDA, null);
        res.moveToFirst();
        int id;
        String idUsuario;
        int monedas;
        String fecha;
        **double latitud;
        double longitud;**
        Partida partida;
        while (!res.isAfterLast()) {
            id = res.getInt(res.getColumnIndex(COLUMN_ID));
            idUsuario = res.getString(res.getColumnIndex(COLUMN_USUARIO));
            monedas = res.getInt(res.getColumnIndex(COLUMN_MONEDAS));
            fecha = res.getString(res.getColumnIndex(COLUMN_FECHA));
            **latitud = res.getDouble(res.getColumnIndex(COLUMN_LATITUD));
            longitud = res.getDouble(res.getColumnIndex(COLUMN_LONGITUD));**
            partida = new Partida(monedas, idUsuario, latitud, longitud);
            partida.setId(id);
            partida.setFecha(fecha);
            array_list.add(partida);
            res.moveToNext();
        }
        return array_list;
    }



    public Partida listarUno(int id) throws SQLiteException {
        SQLiteDatabase db = this.getReadableDatabase();
        Cursor res = db.rawQuery("select * from " + TABLE_PARTIDA + " WHERE " + COLUMN_ID + "=?", new String[]{Integer.toString(id)});
        res.moveToFirst();
        String idUsuario;
        int monedas;
        String fecha;
        **double latitud;
        double longitud;**
        Partida partida = null;
        while (!res.isAfterLast()) {
            id = res.getInt(res.getColumnIndex(COLUMN_ID));
            idUsuario = res.getString(res.getColumnIndex(COLUMN_USUARIO));
            monedas = res.getInt(res.getColumnIndex(COLUMN_MONEDAS));
            fecha = res.getString(res.getColumnIndex(COLUMN_FECHA));
            **latitud = res.getDouble(res.getColumnIndex(COLUMN_LATITUD));
            longitud = res.getDouble(res.getColumnIndex(COLUMN_LONGITUD));**
            **partida = new Partida(monedas, idUsuario, latitud, longitud);**
            partida.setId(id);
            partida.setFecha(fecha);
            res.moveToNext();
        }
        return partida;
    }

    public List<Partida> obtenerRanking() {
        List<Partida> ranking = new ArrayList<>();
        String selectQuery = "SELECT "+COLUMN_ID+", "+COLUMN_USUARIO+", "+COLUMN_MONEDAS+", "+COLUMN_FECHA+
                ", **"+COLUMN_LATITUD+", "+COLUMN_LONGITUD+"** FROM "+TABLE_PARTIDA +
                " JOIN ( SELECT "+COLUMN_USUARIO+" AS aux_usuario, MAX("+COLUMN_MONEDAS+") AS max_monedas " +
                "       FROM "+TABLE_PARTIDA+" GROUP BY "+COLUMN_USUARIO +
                "       ) AS aux " +
                " ON "+COLUMN_USUARIO+" = aux.aux_usuario AND "+COLUMN_MONEDAS+
                " = aux.max_monedas " +
                " ORDER BY "+COLUMN_MONEDAS+" DESC, "+ COLUMN_FECHA + " ASC";
        /**
        String selectQuery = "SELECT * FROM ( SELECT " + COLUMN_ID + ", " +
                COLUMN_USUARIO + ", "+  COLUMN_MONEDAS + ", " + COLUMN_FECHA +
                " , ROW_NUMBER () OVER (PARTITION BY "+ COLUMN_USUARIO +" ORDER BY "+ COLUMN_MONEDAS + " DESC) RowNum" +
                " FROM " + TABLE_PARTIDA +
                " ) t"+
                " WHERE RowNum=1 ORDER BY "+COLUMN_MONEDAS+" DESC";
         **/
        SQLiteDatabase db = this.getWritableDatabase();
        Cursor res = db.rawQuery(selectQuery, null);
        res.moveToFirst();
        int id;
        String idUsuario;
        int monedas;
        String fecha;
        Partida partida;
        **double latitud;
        double longitud;**
        if(res.moveToFirst()) {
            do{
                id = res.getInt(res.getColumnIndex(COLUMN_ID));
                idUsuario = res.getString(res.getColumnIndex(COLUMN_USUARIO));
                monedas = res.getInt(res.getColumnIndex(COLUMN_MONEDAS));
                fecha = res.getString(res.getColumnIndex(COLUMN_FECHA));
                **latitud = res.getDouble(res.getColumnIndex(COLUMN_LATITUD));
                longitud = res.getDouble(res.getColumnIndex(COLUMN_LONGITUD));**
                partida = new Partida(monedas, idUsuario, latitud, longitud);
                partida.setId(id);
                partida.setFecha(fecha);
                ranking.add(partida);
                res.moveToNext();
            }while (!res.isAfterLast());
        }
        res.close();
        db.close();
        return ranking;
    }`
**Vista/Ranking/mostrarRanking** Añadimos las siguientes dos líneas en la funcion para printear la ubicacion:
`textViewFecha.setText("Fecha: " + partida.getFecha() + " Latitud: " + String.valueOf(partida.getLatitud()) + " Longitud: " + String.valueOf(partida.getLongitud()));
`
**AndroidManifest** Permisos para recoger la altitud y longitud:
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />`
