### ISSUE TITLE
ISMA: Añadir una sección de ayuda utilizando un webview.

### ISSUE THREAD

**Issue by Jve386** [Jve386/NativeNinjas-Apps#21]

**Comment by ismaels931** [comment]
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ayuda</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            padding: 20px;
        }
        h1 {
            color: #333;
        }
        p {
            color: #666;
        }
    </style>
</head>
<body>
<h1>Guía de Ayuda</h1>
<p>Bienvenido a la sección de ayuda de nuestra aplicación.</p>
<h2>Comenzar</h2>
<p>Al clicar este botón se accede a una pantalla en la que puedes poner tu nombre e iniciar una partida.</p>
<h2>Ranking</h2>
<p>En esta pantalla se puede visualizar un listado con los usuarios que han jugado y sus puntuaciones.</p>
<h2>Configuración</h2>
<p>Aquí puedes encontrar la configuración para personalizar tu experiencia de usuario, como la música de fondo o el idioma.</p>
</body>
</html>

**Comment by ismaels931** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/black"
    android:backgroundTint="@color/teal_700"
    android:orientation="vertical">

    <WebView
        android:id="@+id/webview_help"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <Button
        android:id="@+id/btnAtras"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/webview_help"
        android:layout_centerHorizontal="true"
        android:text="@string/text5_ajustes"
        android:layout_marginTop="-70dp">
    </Button>

</RelativeLayout>
