### ISSUE TITLE
ISMA: Implementar aspectos de internacionalización y localización. La traducción de la interfície de usuario se realizará en diversos idiomas, con el inglés obligatorio.

### ISSUE THREAD

**Issue by Jve386** [Jve386/NativeNinjas-Apps#22]

**Comment by ismaels931** [comment]
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">RockPaperScissors</string>

    <string name="text1_splash">APP Product 1</string>
    <string name="text2_splash">Powered by NativeNinjas</string>

    <string name="btn1_main">Start</string>
    <string name="btn2_main">Ranking</string>
    <string name="btn3_main">Settings</string>
    <string name="btn4_main">Exit</string>

    <string name="btn_ranking">Back</string>

    <string name="text1_jugador">Rock, paper or scissors</string>
    <string name="field1_jugador">Enter your name:</string>
    <string name="btn1_jugador">Play</string>
    <string name="btn2_jugador">Exit</string>

    <string name="text1_partida">Anonymous enemy</string>

    <string name="text1_ajustes">SETTINGS</string>
    <string name="text2_ajustes">Choose background song:</string>
    <string name="text3_ajustes">Turn music on/off:</string>
    <string name="text4_ajustes">Choose a language:</string>
    <string name="text5_ajustes">Back</string>
    <string name="text6_ajustes">Help</string>

    <string name="btn1_final">Retry</string>
    <string name="btn2_final">Back to menu</string>
    <string name="btn3_final">Exit</string>
    <string name="btn4_final">Screenshot</string>
</resources>

**Comment by ismaels931** [comment]
Spinner spinnerOptions = findViewById(R.id.spinner_options);

        // Definir los elementos del menú
        String[] options = {"Español", "Inglés", "Catalán"};

        // Crear un adaptador para el Spinner
        ArrayAdapter<String> adapter = new ArrayAdapter<>(this, android.R.layout.simple_spinner_item, options);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

        // Asignar el adaptador al Spinner
        spinnerOptions.setAdapter(adapter);

        spinnerOptions.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parentView, View selectedItemView, int position, long id) {
                // Acciones a realizar cuando se selecciona una opción
                String selectedOption = options[position];
                // Aquí puedes realizar las acciones específicas para cada opción seleccionada
                switch (selectedOption) {
                    case "Español":
                        // Acciones para la opción 1
                        cambiarIdioma(AjustesActivity.this, "es");
                        break;
                    case "Inglés":
                        // Acciones para la opción 2
                        cambiarIdioma(AjustesActivity.this, "en");
                        break;
                    case "Catalán":
                        // Acciones para la opción 3
                        cambiarIdioma(AjustesActivity.this, "ca");
                        break;
                    default:
                        // Acciones predeterminadas
                        break;
                }
            }

            @Override
            public void onNothingSelected(AdapterView<?> parentView) {
                // Acciones a realizar cuando no se selecciona ninguna opción (si es necesario)
            }

        });
    }

    public void cambiarIdioma(Context context, String codigoIdioma) {
        Locale nuevaloc = new Locale(codigoIdioma);
        Locale.setDefault(nuevaloc);

        Configuration configuration = getResources().getConfiguration();
        configuration.setLocale(nuevaloc);
        getResources().updateConfiguration(configuration, getResources().getDisplayMetrics());
    }

**Comment by ismaels931** [comment]
<Spinner
        android:id="@+id/spinner_options"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_below="@id/toggleMusicaFondo"
        android:layout_marginTop="10dp"/>
