### ISSUE TITLE
Base de datos Firebase y aplicarlo en el desarrollo de la app propuesta. Autenticar los jugadores con una cuenta de Google en Firebase.

### ISSUE THREAD

**Issue by Jve386** [Jve386/NativeNinjas-Apps#36]

**Comment by javier78sm** [comment]
Base de datos Firebase y aplicarlo en el desarrollo de la aplicación propuesta. 

Conectarse a Firebase y enlazar App con Firebase y configurar la aplicación con las dependencias que te indica en el tutorial.



Autenticar los jugadores con una cuenta de Google en Firebase.

1. Desde el icono Authentication / metodo de acceso / Proveedores de acceso / agregar proveedor nuevo: se escoge Google.
![image](https://github.com/Jve386/NativeNinjas-Apps/assets/131386757/a513fdcb-324a-4d3d-ac56-a787cf0cbb8c)
![image](https://github.com/Jve386/NativeNinjas-Apps/assets/131386757/1c8068f8-30ba-4e69-b1a9-a749608590bb)
